name: Actualizador Automático de Videos
on:
  # schedule:
  #   - cron: '59 */23 * * *' 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4 # Actualizado de v3 a v4

      - name: Configurar Python
        uses: actions/setup-python@v5 # Actualizado de v4 a v5
        with:
          python-version: '3.11' # Versión más moderna

      - name: Instalar librerías
        run: pip install -r requirements.txt

      - name: Ejecutar script de recolección
        run: python fetch_videos.py

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name 'VideoBot'
          git config --global user.email 'bot@github.com'
          git add videos.json
          git commit -m "Lista de videos actualizada" || exit 0
          git push
